ntb_perf: Fix 64-bit division on 32-bit architectures
When compiling for a 32-bit architecture, such as arm, an error occurs
during modpost:

  ERROR: modpost: "__aeabi_uldivmod" [drivers/ntb/test/ntb_perf.ko] undefined!

The tries member of struct perf_thread is u64 so a 64-bit division
helper is needed. Use div_u64_rem() to get the remainder of the division
so that it can be checked against zero.

Fixes: dc150dfb081f ("ntb_perf: extend with burst latency measurement")
Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Nathan Chancellor <nathan@kernel.org>
Signed-off-by: Jon Mason <jdmason@kudzu.us>