NFS: Fix a compile issue in nfs_root
Stephen Rothwell reports:

 > /home/test/linux-2.6/fs/nfs/nfsroot.c: In function 'nfs_root_debug':
 > /home/test/linux-2.6/fs/nfs/nfsroot.c:110:2: error: 'nfs_debug'
 > undeclared (first use in this function)
 [...]

Which is caused by commit
306a075362a288683f6346185f97dd0e06df19da (NFS: Allow NFSROOT
debugging messages to be enabled dynamically)

Fix is to disable this code when RPC_DEBUG is disabled.

Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
Signed-off-by: Trond Myklebust <Trond.Myklebust@netapp.com>
Cc: Zimny Lech <napohybelskurwysynom2010@gmail.com>
Cc: Linus Torvalds <torvalds@linux-foundation.org>
Cc: Charles Edward Lever <Chuck.Lever@oracle.com>
LKML-Reference: <1288096333.3123.9.camel@heimdal.trondhjem.org>
Signed-off-by: Ingo Molnar <mingo@elte.hu>