x86/xen: Fix compilation error due to missing nopvspin declaration
 arch/x86/xen/smp_hvm.c: In function 'xen_hvm_smp_init':
 arch/x86/xen/smp_hvm.c:77:3: error: 'nopvspin' undeclared (first use in this function)
    nopvspin = true;
    ^~~~~~~~
 arch/x86/xen/smp_hvm.c:77:3: note: each undeclared identifier is reported only once for each function it appears in
 make[4]: *** [scripts/Makefile.build:279: arch/x86/xen/smp_hvm.o] Error 1
 make[3]: *** [scripts/Makefile.build:496: arch/x86/xen] Error 2
 make[3]: *** Waiting for unfinished jobs....
 make[2]: *** [Makefile:1805: arch/x86] Error 2
 make[2]: *** Waiting for unfinished jobs....

Fixes: 3d7746bea925 ("x86/xen: Fix xen_hvm_smp_init() when vector callback not available")
Signed-off-by: Leon Romanovsky <leonro@nvidia.com>
Signed-off-by: Saeed Mahameed <saeedm@nvidia.com>