x86/cpufeature: Always provide the cache_line_size definition via <asm/cache.h>
The 'cache_line_size' definition is in <asm/cpufeature.h>, but it's picked up
by <linux/cache.h> via <asm/cache.h> - which dependency can go missing:

   net/smc/smc_ib.c:825:19: error: implicit declaration of function ‘cache_line_size’ [-Werror=implicit-function-declaration]

Always include <asm/cpufeature.h> in <asm/cache.h> and move over the
cache_line_size definition.

Signed-off-by: Ingo Molnar <mingo@kernel.org>