<not for upstream> usb_wwan: Fix build error
commit 16871dcac74c (usb_wwan: error case of resume) added a
build error if CONFIG_PM_RUNTIME is not defined.

  CC [M]  drivers/usb/serial/usb_wwan.o
drivers/usb/serial/usb_wwan.c: In function ‘play_delayed’:
drivers/usb/serial/usb_wwan.c:702: error: ‘struct
dev_pm_info’ has no member named ‘usage_count’

I suspect we should use pm_runtime_put_noidle() instead

Signed-off-by: Eric Dumazet <eric.dumazet@gmail.com>
Cc: Greg Kroah-Hartman <gregkh@suse.de>
Cc: Oliver Neukum <oneukum@suse.de>
LKML-Reference: <1300341100.10164.523.camel@edumazet-laptop>
Signed-off-by: Ingo Molnar <mingo@elte.hu>