platform/x86: Msi-laptop depends on SERIO_I8042
msi-laptop uses i8042_*() interfaces, so it should depend on
SERIO_I8042.  E.g., when SERIO_I8042=m and MSI_LAPTOP=y:

 msi-laptop.c:(.text+0x18a7fe): undefined reference to `i8042_install_filter'
 msi-laptop.c:(.init.text+0xd69d): undefined reference to `i8042_remove_filter'
 msi-laptop.c:(.exit.text+0x19c3): undefined reference to `i8042_remove_filter'

Signed-off-by: Randy Dunlap <randy.dunlap@oracle.com>
Cc: Matthew Garrett <mjg@redhat.com>
Cc: Stephen Rothwell <sfr@canb.auug.org.au>
Cc: Lennart Poettering <mzxreary@0pointer.de>
LKML-Reference: <20100523163317.d1224414.randy.dunlap@oracle.com>
Signed-off-by: Ingo Molnar <mingo@elte.hu>
Cc: Lennart Poettering <mzxreary@0pointer.de>