net/sctp/sysctl.c: Remove dead strategy handler
Fix:

>  net/sctp/sysctl.c:251: error: unknown field 'strategy' specified in initializer
>  net/sctp/sysctl.c:251: error: 'sysctl_intvec' undeclared here (not in a function)

That's interaction with the strategy handler removal from Eric.
I think  the patch below will do the trick - the callsites have
been updated  already to use proc_handler, so ->handler was a
dead field.

Signed-off-by: Ingo Molnar <mingo@elte.hu>
Cc: torvalds@linux-foundation.org
Cc: David Miller <davem@davemloft.net>
Cc: Eric W. Biederman <ebiederm@xmission.com>
LKML-Reference: <20091208195209.GA30947@elte.hu>
Signed-off-by: Ingo Molnar <mingo@elte.hu>