nls: Fix build failure when CONFIG_NLS is set to 'm' by allmodconfig
This patch fixes the following build breakage introduced by the
patch '[PATCH V3] Export ACPI _DSM provided firmware instance
number and string to sysfs'.

 drivers/built-in.o: In function `T.647':
 pci-label.c:(.text+0x28514): undefined reference to `utf16s_to_utf8s'

This happens because 'make allmodconfig' sets CONFIG_NLS=m and
makes 'utf16s_to_utf8s` unavailable to drivers/pci/pci-label.o
which is built into vmlinux.

This is fixed by making fs/nls/nls_base.c compile conditionally
into vmlinux by introducing a new config option CONFIG_NLS_BASE
which is selected by (ACPI || DMI || NLS).

Signed-off-by: Narendra K <narendra_k@dell.com>
Cc: <mjg@redhat.com>
Cc: <sfr@canb.auug.org.au>
Cc: <Shyam_Iyer@Dell.com>
Cc: <Matt_Domsch@Dell.com>
Cc: <Charles_Rose@Dell.com>
Cc: <Jordan_Hargrave@Dell.com>
Cc: <viro@zeniv.linux.org.uk>
Cc: <jbarnes@virtuousgeek.org>
Link: http://lkml.kernel.org/r/20110223131536.GA16707@fedora14-r610.blr.amer.dell.com
Signed-off-by: Ingo Molnar <mingo@elte.hu>