powerpc/signal32: Fix build error with CONFIG_SPE=y
The recent conversion to user_access_read_begin/end() introduced a
compile break when CONFIG_SPE=y:

  arch/powerpc/kernel/signal_32.c: In function 'restore_user_regs':
  arch/powerpc/kernel/signal_32.c:573:36: error: macro
  "unsafe_copy_from_user" requires 4 arguments, but only 3 given

It's missing the failure label, add it.

Fixes: 627b72bee84d ("powerpc/signal32: Convert restore_[tm]_user_regs() to user access block")
Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>