sound: Fix opti92x-ad1848 build
Fix 'else' placement in ifdef block so that build succeeds:

sound/isa/opti9xx/opti92x-ad1848.c:221: error: 'else' without a
previous 'if'

Signed-off-by: Randy Dunlap <randy.dunlap@oracle.com>
Cc: Jaroslav Kysela <perex@perex.cz>
Cc: Takashi Iwai <tiwai@suse.de>
Cc: Stephen Rothwell <sfr@canb.auug.org.au>
LKML-Reference: <4B9534BA.4020903@oracle.com>
Signed-off-by: Ingo Molnar <mingo@elte.hu>