headers/prep: kprobes/test: Make it depend on CONFIG_STACKTRACE
This test module depends on stacktrace functionality:

  lib/test_kprobes.c: In function ‘stacktrace_return_handler’:
  lib/test_kprobes.c:229:8: error: implicit declaration of function ‘stack_trace_save’; did you mean ‘stacktrace_driver’? [-Werror=implicit-function-declaration]
  lib/test_kprobes.c:243:8: error: implicit declaration of function ‘stack_trace_save_regs’; did you mean ‘stacktrace_target’? [-Werror=implicit-function-declaration]

Enforce this dependency at the Kconfig level.

Signed-off-by: Ingo Molnar <mingo@kernel.org>