vivi: Fix depends again
My previous patch to depend on FONTS was not sufficient since
FONTS is boolean.  VIDEO_VIVI needs to depend on a tristate so
that it won't be enabled as =y when framebuffer is built as
modular, so modify it to depend on the same symbols that FONTS
depends on, which are FRAMEBUFFER_CONSOLE || STI_CONSOLE.

Fixes this build error when VIDEO_VIVI=y and
FRAMEBUFFER_CONSOLE=m: vivi.c:(.init.text+0x7205): undefined reference to `find_font'

Signed-off-by: Randy Dunlap <randy.dunlap@oracle.com>
Cc: Stephen Rothwell <sfr@canb.auug.org.au>
Cc: Mauro Carvalho Chehab <mchehab@infradead.org>
LKML-Reference: <20100614170319.7647ab62.randy.dunlap@oracle.com>
Signed-off-by: Ingo Molnar <mingo@elte.hu>