mm-hugetlb-introduce-hugetlb_walk-checkpatch-fixes
ERROR: code indent should use tabs where possible
#267: FILE: mm/page_vma_mapped.c:172:
+                 * All callers that get here will already hold the$

ERROR: code indent should use tabs where possible
#268: FILE: mm/page_vma_mapped.c:173:
+                 * i_mmap_rwsem.  Therefore, no additional locks need to be$

ERROR: code indent should use tabs where possible
#269: FILE: mm/page_vma_mapped.c:174:
+                 * taken before calling hugetlb_walk().$

total: 3 errors, 0 warnings, 211 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

NOTE: Whitespace errors detected.
      You may wish to use scripts/cleanpatch or scripts/cleanfile

./patches/mm-hugetlb-introduce-hugetlb_walk.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Peter Xu <peterx@redhat.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>