squashfs-implement-readahead-checkpatch-fixes
ERROR: need consistent spacing around '&' (ctx:WxO)
#54: FILE: fs/squashfs/file.c:505:
+	loff_t start = readahead_pos(ractl) &~ mask;
 	                                    ^

ERROR: space prohibited after that '~' (ctx:OxW)
#54: FILE: fs/squashfs/file.c:505:
+	loff_t start = readahead_pos(ractl) &~ mask;
 	                                     ^

total: 2 errors, 0 warnings, 109 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

./patches/squashfs-implement-readahead.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Hsin-Yi Wang <hsinyi@chromium.org>
Cc: Phillip Lougher <phillip@squashfs.org.uk>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>