<not-for-merge> ahci: Fix "filter FPDMA non-zero offset enable for Aspire 3810T" on !CONFIG_ATA_ACPI
Commit f80ae7e ("ahci: filter FPDMA non-zero offset enable for Aspire
3810T") introduced a new build breakage:

  drivers/ata/ahci.c: In function ‘ahci_gtf_filter_workaround’:
  drivers/ata/ahci.c:2927: error: ‘struct ata_device’ has no member named ‘gtf_filter’
  make[2]: *** [drivers/ata/ahci.o] Error 1
  make[1]: *** [drivers/ata] Error 2
  make[1]: *** Waiting for unfinished jobs....

As the acpi taskfile command filter support is a property of
libata-acpi - so the ata_device::gtf_filter field only exists
under CONFIG_ATA_ACPI.

Add the trivial #ifdef to turn ahci_gtf_filter_workaround()
into a NOP on !CONFIG_ATA_ACPI.

Cc: Marcus Meissner <meissner@novell.com>
Cc: Jeff Garzik <jgarzik@redhat.com>
Signed-off-by: Ingo Molnar <mingo@elte.hu>