samples/bpf: Add XDP meta data sampling to xdp_sample_pkts
Add support for XDP meta data, a special compilation flag was introduced
since XDP meta data with BTF requires a driver specific header file.

to compile with XDP meta data support:

 # Compile samples with XDP metadata support and latest bpftool

$ XDP_MD_BTF=1 make  M=samples/bpf
1 error generated.
  CLANG-bpf  samples/bpf/xdp_sample_pkts_kern.o
samples/bpf/xdp_sample_pkts_kern.c:60:10: fatal error: 'xdp_md_btf.h' file not found

 # this will fail due to missing driver md header file
 # to generate it :
$ /usr/local/sbin/bpftool net xdp md_btf cstyle dev mlx0 > samples/bpf/xdp_md_btf.h
 # Now again:
$ XDP_MD_BTF=1 make  M=samples/bpf

 # Run Samples:
$ /usr/local/sbin/bpftool net xdp set dev mlx0 md_btf on
$ ./samples/bpf/xdp_sample_pkts mlx0
Found xdp md prog
Flwo mark: 0x2a, hash32: 0x46bb6ac7, Ethernet hdr: 52 54 00 00 00 02 f6 a3 6e 59 16 83 08 00
Flwo mark: 0x2a, hash32: 0x46bb6ac7, Ethernet hdr: 52 54 00 00 00 02 f6 a3 6e 59 16 83 08 00

Issue: 2114293
Change-Id: If1e774dc2a1285a3b9bc7c133feeca8078a46c8d
Signed-off-by: Saeed Mahameed <saeedm@mellanox.com>