hid: Roccat modules interdependencies
hid-roccat-kone calls the hid-roccat module interfaces,
so the former should depend on or select the latter to prevent
build errors, like:

hid-roccat-kone.c:(.text+0x133ed2): undefined reference to
`roccat_report_event' hid-roccat-kone.c:(.text+0x133fa8):
undefined reference to `roccat_disconnect'
hid-roccat-kone.c:(.text+0x1353be): undefined reference to `roccat_connect'

Signed-off-by: Randy Dunlap <randy.dunlap@oracle.com>
Cc: Stephen Rothwell <sfr@canb.auug.org.au>
Cc: Jiri Kosina <jkosina@suse.cz>
Cc: Stefan Achatz <erazor_de@users.sourceforge.net>
LKML-Reference: <20100527090706.6c2bc555.randy.dunlap@oracle.com>
Signed-off-by: Ingo Molnar <mingo@elte.hu>