headers/deps: net: Move the ____cacheline_aligned_in_smp attribute of 'struct netdev_rx_queue' to an easier to debug position
If <linux/cache.h> is removed from <linux/netdevice_api.h>,
then the build will succeed on GCC, only to fail at link time, with hundreds
of obscure warnings that don't pinpoint the true origin of the error:

      ld: net/sctp/tsnmap.o:(.bss+0x0): multiple definition of `____cacheline_aligned_in_smp'; init/do_mounts_rd.o:(.bss+0x0): first defined here
      ....

Move the attribute to the head of the definition, in which case
a missing <linux/cache.h> inclusion creates an immediate build failure.

[ Fixes by Nathan Chancellor ]

Fixed-by: Nathan Chancellor <nathan@kernel.org>
Signed-off-by: Ingo Molnar <mingo@kernel.org>