headers/prep: genirq: Move ____cacheline_internodealigned_in_smp attributes to before the structure definition
Make it easier to discover missing dependencies of <linux/cache.h>,
if the ____cacheline_internodealigned_in_smp is at the end of a
structure definition, and <linux/cache.h> is missing, it will result
in obscure linker errors that are difficult to track down:

  ld: arch/x86/kernel/vsmp_64.o:(.bss+0x0): multiple definition of `____cacheline_internodealigned_in_smp'; arch/x86/kernel/apic/apic_common.o:(.bss+0x0): first defined here

If the attributes are at the beginning, the bugs become a lot
more clear:

  ./include/linux/irqdesc.h: In function ‘irq_desc_get_irq’:
  ./include/linux/irqdesc.h:130:13: error: invalid use of undefined type ‘struct irq_desc’

No change in generated code.

Signed-off-by: Ingo Molnar <mingo@kernel.org>