headers/prep: Rename constants: SOCK_DESTROY => SOCK_DIAG_SOCK_DESTROY
Address namespace collision between netdiag's SOCK_DESTROY and the SOCK_DESTROY socket state.

Rename the API command to SOCK_DIAG_SOCK_DESTROY, so that they don't end up colliding
with <net/sock.h>'s SOCK_DESTROY when the headers are included at once:

   CC      net/bpf/test_run.o
 In file included from ./include/net/bpf_sk_storage.h:13,
                  from net/bpf/test_run.c:12:
 ./include/uapi/linux/sock_diag.h:8:22: error: expected identifier before numeric constant
     8 | #define SOCK_DESTROY 21
       |                      ^~
 ./include/net/sock_api.h:308:2: note: in expansion of macro ‘SOCK_DESTROY’
   308 |  SOCK_DESTROY,
       |  ^~~~~~~~~~~~

Signed-off-by: Ingo Molnar <mingo@kernel.org>