scsi: RAID_ATTRS depends on SCSI
raid_class uses scsi interfaces, so it should depend on SCSI.
Otherwise build errors occur when RAID_ATTRS=y and SCSI=m:

  ERROR: "raid_class_release" [drivers/scsi/mpt2sas/mpt2sas.ko] undefined!
  ERROR: "raid_class_attach"
  [drivers/scsi/mpt2sas/mpt2sas.ko] undefined!

Signed-off-by: Randy Dunlap <randy.dunlap@oracle.com>
Cc: Stephen Rothwell <sfr@canb.auug.org.au>
Cc: James E.J. Bottomley <James.Bottomley@suse.de>
LKML-Reference: <20100221194636.ef885e5a.rdunlap@xenotime.net>
Signed-off-by: Ingo Molnar <mingo@elte.hu>