mm/memory-failure: fix redefinition of mf_generic_kill_procs
If CONFIG_HUGETLB_PAGE=n, building fails:

mm/memory-failure.c:1805:19: error: redefinition of `mf_generic_kill_procs'
 static inline int mf_generic_kill_procs(unsigned long long pfn, int flags,
                   ^~~~~~~~~~~~~~~~~~~~~
mm/memory-failure.c:1564:12: note: previous definition of `mf_generic_kill_procs' was here
 static int mf_generic_kill_procs(unsigned long long pfn, int flags,

This patch fixes that.

Link: https://lkml.kernel.org/r/20220628112143.1170473-1-zhengbin13@huawei.com
Fixes: 4184e8d7d056 ("mm-factor-helpers-for-memory_failure_dev_pagemap-fix")
Signed-off-by: Zheng Bin <zhengbin13@huawei.com>
Cc: Shiyang Ruan <ruansy.fnst@fujitsu.com>
Cc: Naoya Horiguchi <naoya.horiguchi@nec.com>
Cc: Miaohe Lin <linmiaohe@huawei.com>
Cc: gaochao <gaochao49@huawei.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>