headers/prep: Avoid stack_canary_offset namespace collision
drivers/misc/lkdm/ uses a stack_canary_offset local variable, which
clashes with the same name generated in arch/x86/kernel/asm-offsets_64.c.

This becomes a problem if asm-offsets.h is included more broadly than just
architecture headers:

    In file included from ./include/linux/sched/per_task.h:48,
                     from ./include/linux/sched.h:12,
                     from drivers/misc/lkdtm/bugs.c:10:
    ./include/generated/asm-offsets.h:37:29: error: expected identifier or ‘(’ before numeric constant
       37 | #define stack_canary_offset 40 /* offsetof(struct fixed_percpu_data, stack_canary) */
          |                             ^~
    drivers/misc/lkdtm/bugs.c:156:22: note: in expansion of macro ‘stack_canary_offset’
      156 | static unsigned long stack_canary_offset;

Prefix the x86 version with x86_ to avoid the namespace collision.

Signed-off-by: Ingo Molnar <mingo@kernel.org>