of: Define NO_IRQ globally when not supplied by the architecture
Since the application of the commit below the PATA OF platform
driver may now be built on x86 systems:

  ata: Make pata_of_platform.c compile again and work on non-PPC platforms

This leads to the following build failure on 32bit x86 builds:

  .../drivers/ata/pata_of_platform.c: In function 'pata_of_platform_probe':
  .../drivers/ata/pata_of_platform.c:55: error: 'NO_IRQ' undeclared
					(first use in this function)

This occurs because x86 does not supply a definition for NO_IRQ.
However if we examine drivers/of/irq.c we already supply a
default value for NO_IRQ where not specified by the
architecture.  Fix the build failure by pulling this default
value up to include/linux/of_irq.h.

Signed-off-by: Andy Whitcroft <apw@canonical.com>
Cc: Linux Torvalds <torvalds@linux-foundation.org>
Cc: Grant Likely <grant.likely@secretlab.ca>
Cc: Rob Herring <rob.herring@calxeda.com>
Cc: devicetree-discuss@lists.ozlabs.org
Link: http://lkml.kernel.org/r/1320752666-15553-1-git-send-email-apw@canonical.com
Signed-off-by: Ingo Molnar <mingo@elte.hu>