IR: Jvc-decoder needs BITREVERSE
ir-jvc-decoder uses bitreverse interfaces, so it should select
BITREVERSE.

 ir-jvc-decoder.c:(.text+0x550bc): undefined reference to `byte_rev_table'
 ir-jvc-decoder.c:(.text+0x550c6): undefined reference to `byte_rev_table'

Signed-off-by: Randy Dunlap <randy.dunlap@oracle.com>
Cc: Mauro Carvalho Chehab <mchehab@infradead.org>
Cc: Stephen Rothwell <sfr@canb.auug.org.au>
Cc: Jarod Wilson <jarod@redhat.com>
Cc: David =?ISO-8859-1?Q?H=E4rdeman?= <david@hardeman.nu>
LKML-Reference: <20100707164115.1682b172.randy.dunlap@oracle.com>
Signed-off-by: Ingo Molnar <mingo@elte.hu>
Cc: Jarod Wilson <jarod@redhat.com>
Cc: David Härdeman <david@hardeman.nu>
Cc: Mauro Carvalho Chehab <mchehab@infradead.org>