misc/pti.c: Fix build error when PCI is not selected
When you try to build INTEL_MID_PTI without having PCI
enabled. It fails like this-

 CC [M]  drivers/misc/pti.o
 drivers/misc/pti.c: In function ‘pti_pci_remove’:
 drivers/misc/pti.c:410: error: implicit declaration of function ‘pci_release_region’
 drivers/misc/pti.c: In function ‘pti_pci_probe’:
 drivers/misc/pti.c:859: error: implicit declaration of function ‘pci_request_region’

So make INTEL_MID_PTI depend on PCI to fix build error.

Signed-off-by: Tracey Dent <tdent48227@gmail.com>
Cc: gregkh@suse.de
Link: http://lkml.kernel.org/r/20110811162306.GA30710@tj-desktop
Signed-off-by: Ingo Molnar <mingo@elte.hu>