<not-for-uptream> ipmi_si: Fix !CONFIG_ACPI build failure
Today's -tip failed to build because commit
9e368fa011d4e0aa050db348d69514900520e40b ("ipmi: add PNP
discovery (ACPI  namespace via PNPACPI)") from today's upstream
kernel causes the following  build failure on x86, for
CONFIG_ACPI=n && CONFIG_IPMI_SI=y:

 drivers/char/ipmi/ipmi_si_intf.c:3208: error: 'ipmi_pnp_driver' undeclared (first use in this function)
 drivers/char/ipmi/ipmi_si_intf.c:3208: error: (Each undeclared identifier is reported only once
 drivers/char/ipmi/ipmi_si_intf.c:3208: error: for each function it appears in.)
 drivers/char/ipmi/ipmi_si_intf.c:3334: error: 'ipmi_pnp_driver' undeclared (first use in this function)

The reason is that the ipmi_pnp_driver depends on ACPI
facilities and is only  made available under ACPI - while the
registration and unregistration is made  dependent on
CONFIG_PNP:

 #ifdef CONFIG_PNP
 	pnp_register_driver(&ipmi_pnp_driver);
 #endif

The solution is to only register this driver under ACPI. (Also,
the CONFIG_PNP  dependency is not needed because
pnp_register_driver() is stubbed out in the  !CONFIG_PNP case.)

Signed-off-by: Ingo Molnar <mingo@elte.hu>
Cc: Bjorn Helgaas <bjorn.helgaas@hp.com>
Cc: Myron Stowe <myron.stowe@hp.com>
Cc: Len Brown <lenb@kernel.org>
Cc: Linus Torvalds <torvalds@linux-foundation.org>
LKML-Reference: <20091217075025.GA314@elte.hu>
Signed-off-by: Ingo Molnar <mingo@elte.hu>