linux-next: build failure after merge of the maple tree
* broonie@kernel.org <broonie@kernel.org> [220222 19:45]:
> Hi all,
>
> After merging the maple tree, today's linux-next build (KCONFIG_NAME)
> failed like this:
>
> /tmp/next/build/arch/arm64/kernel/elfcore.c: In function 'elf_core_extra_phdrs':
> /tmp/next/build/arch/arm64/kernel/elfcore.c:13:21: error: 'struct mm_struct' has no member named 'mmap'
>    13 |   for (vma = tsk->mm->mmap; vma; vma = vma->vm_next) \
>       |                     ^~
> /tmp/next/build/arch/arm64/kernel/elfcore.c:69:2: note: in expansion of macro 'for_each_mte_vma'
>    69 |  for_each_mte_vma(current, vma)
>       |  ^~~~~~~~~~~~~~~~
> /tmp/next/build/arch/arm64/kernel/elfcore.c:13:43: error: 'struct vm_area_struct' has no member named 'vm_next'
>    13 |   for (vma = tsk->mm->mmap; vma; vma = vma->vm_next) \
>       |                                           ^~
> /tmp/next/build/arch/arm64/kernel/elfcore.c:69:2: note: in expansion of macro 'for_each_mte_vma'
>    69 |  for_each_mte_vma(current, vma)
>       |  ^~~~~~~~~~~~~~~~
> /tmp/next/build/arch/arm64/kernel/elfcore.c: In function 'elf_core_write_extra_phdrs':
> /tmp/next/build/arch/arm64/kernel/elfcore.c:13:21: error: 'struct mm_struct' has no member named 'mmap'
>    13 |   for (vma = tsk->mm->mmap; vma; vma = vma->vm_next) \
>       |                     ^~
> /tmp/next/build/arch/arm64/kernel/elfcore.c:79:2: note: in expansion of macro 'for_each_mte_vma'
>    79 |  for_each_mte_vma(current, vma) {
>       |  ^~~~~~~~~~~~~~~~
> /tmp/next/build/arch/arm64/kernel/elfcore.c:13:43: error: 'struct vm_area_struct' has no member named 'vm_next'
>    13 |   for (vma = tsk->mm->mmap; vma; vma = vma->vm_next) \
>       |                                           ^~
> /tmp/next/build/arch/arm64/kernel/elfcore.c:79:2: note: in expansion of macro 'for_each_mte_vma'
>    79 |  for_each_mte_vma(current, vma) {
>       |  ^~~~~~~~~~~~~~~~
> /tmp/next/build/arch/arm64/kernel/elfcore.c: In function 'elf_core_extra_data_size':
> /tmp/next/build/arch/arm64/kernel/elfcore.c:13:21: error: 'struct mm_struct' has no member named 'mmap'
>    13 |   for (vma = tsk->mm->mmap; vma; vma = vma->vm_next) \
>       |                     ^~
> /tmp/next/build/arch/arm64/kernel/elfcore.c:104:2: note: in expansion of macro 'for_each_mte_vma'
>   104 |  for_each_mte_vma(current, vma)
>       |  ^~~~~~~~~~~~~~~~
> /tmp/next/build/arch/arm64/kernel/elfcore.c:13:43: error: 'struct vm_area_struct' has no member named 'vm_next'
>    13 |   for (vma = tsk->mm->mmap; vma; vma = vma->vm_next) \
>       |                                           ^~
> /tmp/next/build/arch/arm64/kernel/elfcore.c:104:2: note: in expansion of macro 'for_each_mte_vma'
>   104 |  for_each_mte_vma(current, vma)
>       |  ^~~~~~~~~~~~~~~~
> /tmp/next/build/arch/arm64/kernel/elfcore.c: In function 'elf_core_write_extra_data':
> /tmp/next/build/arch/arm64/kernel/elfcore.c:13:21: error: 'struct mm_struct' has no member named 'mmap'
>    13 |   for (vma = tsk->mm->mmap; vma; vma = vma->vm_next) \
>       |                     ^~
> /tmp/next/build/arch/arm64/kernel/elfcore.c:114:2: note: in expansion of macro 'for_each_mte_vma'
>   114 |  for_each_mte_vma(current, vma) {
>       |  ^~~~~~~~~~~~~~~~
> /tmp/next/build/arch/arm64/kernel/elfcore.c:13:43: error: 'struct vm_area_struct' has no member named 'vm_next'
>    13 |   for (vma = tsk->mm->mmap; vma; vma = vma->vm_next) \
>       |                                           ^~
> /tmp/next/build/arch/arm64/kernel/elfcore.c:114:2: note: in expansion of macro 'for_each_mte_vma'
>   114 |  for_each_mte_vma(current, vma) {
>       |  ^~~~~~~~~~~~~~~~
>
> I did not identify the commit which triggered this. I have used the
> maple tree from 20220217 instead.

Hello,

I had generated a fix for this on the 17th and sent it to linux-next
[1].  Alternatively, the patch is inline below.

1: https://lore.kernel.org/all/20220218023650.672072-1-Liam.Howlett@oracle.com/

Thanks,
Liam

----------------------------------------------------------------------
From: "Liam R. Howlett" <Liam.Howlett@oracle.com>
Date: Thu, 17 Feb 2022 21:16:53 -0500
Subject: [PATCH] arm64: Change elfcore for_each_mte_vma() to use VMA iterator

Instead of using the linked list, use the vma iterator.

Signed-off-by: Liam R. Howlett <Liam.Howlett@oracle.com>
Signed-off-by: Mark Brown <broonie@kernel.org>