Revert "codafs: fix compile warning when CONFIG_SYSCTL=n"
This reverts commit 0bc825d240abcaf5ed6e9d59b44215b51718ef5b.

Breaks the build:

  fs/built-in.o: In function `init_coda':
  psdev.c:(.init.text+0x2549): undefined reference to `coda_sysctl_clean'
  fs/built-in.o: In function `exit_coda':
  psdev.c:(.exit.text+0x1bf): undefined reference to `coda_sysctl_clean'
  fs/built-in.o: In function `init_coda_psdev':
  psdev.c:(.text.unlikely+0x21e1): undefined reference to `coda_sysctl_init'

Under !CONFIG_PROC_SYSCTL && CONFIG_CODA_FS=y.

Signed-off-by: Ingo Molnar <mingo@elte.hu>