Revert "platform-drivers: x86: pmic: Restore the dropped buslock/unlock"
This reverts commit 65d7ac038e34702feedad91d0bf597b1f0a4174a.

breaks the allyes64 build:

  drivers/platform/x86/intel_pmic_gpio.c:212:19: error: ‘pmic_irq_buslock’ undeclared here (not in a function)

Signed-off-by: Ingo Molnar <mingo@elte.hu>