x86/platform: Classmate-laptop depends on RFKILL
classmate-laptop uses rfkill interfaces, so it should depend on
RFKILL.  Otherwise, when CONFIG_RFKILL=m, these build errors
happen:

classmate-laptop.c:(.text+0x54b4f2): undefined reference to
`rfkill_unregister' classmate-laptop.c:(.text+0x54b508):
undefined reference to `rfkill_destroy'
classmate-laptop.c:(.text+0x54b71a): undefined reference to
`rfkill_alloc' classmate-laptop.c:(.text+0x54b739): undefined
reference to `rfkill_register'
classmate-laptop.c:(.text+0x54b761): undefined reference to `rfkill_destroy' classmate-laptop.c:(.text+0x54b841): undefined reference to `rfkill_set_sw_state'

Signed-off-by: Randy Dunlap <randy.dunlap@oracle.com>
Cc: Thadeu Lima de Souza Cascardo <cascardo@holoscopio.com>
Cc: Daniel Oliveira Nascimento <don@syst.com.br>
Cc: Matthew Garrett <mjg@redhat.com>
Cc: Stephen Rothwell <sfr@canb.auug.org.au>
LKML-Reference: <20100523151540.68e67298.randy.dunlap@oracle.com>
Signed-off-by: Ingo Molnar <mingo@elte.hu>
Cc:	Thadeu Lima de Souza Cascardo <cascardo@holoscopio.com>
Cc:	Daniel Oliveira Nascimento <don@syst.com.br>
Cc:	platform-driver-x86@vger.kernel.org
Cc:	Matthew Garrett <mjg@redhat.com>