nvme-tcp: memset scatterlist before sg_init_marker it
sg_init_marker's sg need initialized, otherwise report:

[...]
In file included from ../include/linux/dma-mapping.h:10,
                 from ../include/linux/skbuff.h:31,
                 from ../include/net/net_namespace.h:39,
                 from ../include/linux/netdevice.h:37,
                 from ../include/net/sock.h:46,
                 from ../drivers/nvme/host/tcp.c:12:
../drivers/nvme/host/tcp.c: In function ‘nvme_tcp_ddgst_update’:
../include/linux/scatterlist.h:214:16: error: ‘sg.page_link’ is used uninitialized in this function [-Werror=uninitialized]
  214 |  sg->page_link |= SG_END;
      |                ^~
cc1: all warnings being treated as errors
make[4]: *** [../scripts/Makefile.build:287: drivers/nvme/host/tcp.o] Error 1
make[3]: *** [../scripts/Makefile.build:549: drivers/nvme/host] Error 2
make[2]: *** [../scripts/Makefile.build:549: drivers/nvme] Error 2
make[2]: *** Waiting for unfinished jobs....
[...]

Fixes: 3f2304f8c6d6 ("nvme-tcp: add NVMe over TCP host driver")
Reported-by: k2ci <kernel-bot@kylinos.cn>
Signed-off-by: Jackie Liu <liuyun01@kylinos.cn>
Reviewed-by: Sagi Grimberg <sagi@grimberg.me>
Signed-off-by: Christoph Hellwig <hch@lst.de>