mfd/twl4030-codec.c: Fix build failure
Today's linux-next build (powerpc allyesconfig) failed like
this:

drivers/mfd/twl4030-codec.c:29:31: error: linux/i2c/twl4030.h:
No such file or directory

(there were more, but I assume that they all stem form this
one).

Caused by commit 0b83ddebc6e884dc0221358cf68c461520fbdd8e ("MFD:
twl4030: add twl4030_codec MFD as a new child to the core") from
Linus' tree interacting with commit
b07682b6056eb6701f8cb86aa5800e6f2ea7919b ("mfd: Rename twl4030*
driver files to enable re-use") also from Linus' tree. This file
seems to have been missed in the renaming.

I have applied this patch for today (please check):

From: Stephen Rothwell <sfr@canb.auug.org.au>
Date: Tue, 15 Dec 2009 16:33:10 +1100

Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
Cc: Peter Ujfalusi <peter.ujfalusi@nokia.com>
Cc: Linus <torvalds@linux-foundation.org>
Cc: Tony Lindgren <tony@atomide.com>
Cc: Mark Brown <broonie@opensource.wolfsonmicro.com>
Cc: Samuel Ortiz <sameo@linux.intel.com>
LKML-Reference: <20091215164108.45c9d766.sfr@canb.auug.org.au>
Signed-off-by: Ingo Molnar <mingo@elte.hu>