mm-hwpoison-introduce-per-memory_block-hwpoison-counter-fix
>
> All errors (new ones prefixed by >>):
>
>    drivers/base/memory.c: In function 'memory_block_online':
> >> drivers/base/memory.c:186:34: error: 'struct memory_block' has no member named 'nr_hwpoison'
>      186 |         if (atomic_long_read(&mem->nr_hwpoison))
>          |                                  ^~
>    drivers/base/memory.c: In function 'remove_memory_block_devices':
>    drivers/base/memory.c:870:61: error: 'struct memory_block' has no member named 'nr_hwpoison'
>      870 |                 clear_hwpoisoned_pages(atomic_long_read(&mem->nr_hwpoison));
>          |                                                             ^~
>

I should've used the accessor memblk_nr_poison() to acccess to
->nr_hwpoison.

Link: https://lkml.kernel.org/r/20220923081827.GA1357512@ik1-406-35019.vs.sakura.ne.jp
Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>