ext4: Fix !CONFIG_EXT4_FS_XATTR build failure
Today's -tip fails to build due to upstream commit 5dabfc7
("ext4: rename  {exit,init}_ext4_*() to ext4_{exit,init}_*()"),
on all[yes/mod]config with  CONFIG_EXT4_FS_XATTR disabled:

  fs/ext4/super.c:4776: error: implicit declaration of function ‘ext4_init_xattr’

Commit 5dabfc7 renamed init_ext4_xattr to ext4_init_xattr but
forgot to update the  definition in fs/ext4/xattr.h. The patch
below fixes it.

Cc: Theodore Ts'o <tytso@mit.edu>
Cc: Linus Torvalds <torvalds@linux-foundation.org>
LKML-Reference: <20101028075631.GA7690@elte.hu>
Signed-off-by: Ingo Molnar <mingo@elte.hu>