ath11k: fix kbuild test robot warnings
Fixes: commit d25cb35c6f10ac1a9f ("ath11k: add support for FW stats via WMI")

Fix below warnings in this patch

drivers/net//wireless/ath/ath11k/debug.c: In function 'ath11k_open_pdev_stats':
>> drivers/net//wireless/ath/ath11k/debug.c:358:8: error: implicit declaration of function 'vmalloc'; did you mean 'kvmalloc'? [-Werror=implicit-function-declaration]
     buf = vmalloc(ATH11K_FW_STATS_BUF_SIZE);
           ^~~~~~~
           kvmalloc
   drivers/net//wireless/ath/ath11k/debug.c:358:6: warning: assignment to 'void *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
     buf = vmalloc(ATH11K_FW_STATS_BUF_SIZE);
         ^
>> drivers/net//wireless/ath/ath11k/debug.c:383:2: error: implicit declaration of function 'vfree'; did you mean 'kvfree'? [-Werror=implicit-function-declaration]
     vfree(buf);
     ^~~~~
     kvfree
   drivers/net//wireless/ath/ath11k/debug.c: In function 'ath11k_open_vdev_stats':
   drivers/net//wireless/ath/ath11k/debug.c:429:6: warning: assignment to 'void *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
     buf = vmalloc(ATH11K_FW_STATS_BUF_SIZE);
         ^
   drivers/net//wireless/ath/ath11k/debug.c: In function 'ath11k_open_bcn_stats':
   drivers/net//wireless/ath/ath11k/debug.c:502:6: warning: assignment to 'void *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
     buf = vmalloc(ATH11K_FW_STATS_BUF_SIZE);
         ^
   drivers/net//wireless/ath/ath11k/debug.c: In function 'ath11k_open_peer_stats':
   drivers/net//wireless/ath/ath11k/debug.c:586:6: warning: assignment to 'void *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
     buf = vmalloc(ATH11K_FW_STATS_BUF_SIZE);
         ^
Below warning is already fixed by commit 191574c12632901577 ("ath11k: fix invalid ar->data_lock access")

drivers/net//wireless/ath/ath11k/debug.c: In function 'ath11k_debug_fw_stats_process':
   drivers/net//wireless/ath/ath11k/debug.c:168:17: warning: 'ar' may be used uninitialized in this function [-Wmaybe-uninitialized]
     struct ath11k *ar;
                    ^~
Signed-off-by: Sathishkumar Muruganandam <murugana@codeaurora.org>
Signed-off-by: Kalle Valo <kvalo@codeaurora.org>