perf tools: Add probing for the XED disassembler library
Can be downloaded from https://github.com/intelxed/xed

v2: Hide. Require XED=1 to enable. Add XED_DIR
v3: Remove -lxed from probe all. Don't touch FEATURE_DISPLAY.
v4: Move to FEATURE_FLAGS_BASIC

Committer Notes:

From https://intelxed.github.io/:

 ---
The X86 Encoder Decoder (XED), is a software library (and associated
headers) for encoding and decoding X86 (IA32 and Intel64) instructions.
The decoder takes sequences of 1-15 bytes along with machine mode
information and produces a data structure describing the opcode,
operands, and flags. The encoder takes a similar data structure and
produces a sequence of 1 to 15 bytes. Disassembly is essentially a
printing pass on the data structure.

XED is the encoder/decoder used by Pin and the Intel® Software
Development Emulator (SDE). XED is used by the ASIM performance model,
ZSIM, Intel® VTune Amplifier, IACA, as well as in projects at McAfee,
Wind River, and many other projects inside and outside Intel.

XED supports the notion of layers of instructions. As new instructions
are made public corresponding to future processors, the associated
layers are added to the tables of instructions in the "datafiles"
subdirectory. (Intel announces and documents instructions in the ISE and
SDM documents typically).
 ---

XED License: Apache, version 2.0.

Also remove it from test-all.c, since it is not normally available on
distros at this time and not selected by default.

For the same reason, move it from FEATURE_TESTS_BASIC to
FEATURE_TESTS_EXTRA, to avoid always trying to build
tools/build/feature/test-xed.c.

One has to define XED=1 to build WITH the XED disassembler to be used in
'perf script'.  It is also possible to set XED_DIR=/path to set the XED
directory.

Added the XED_DIR to CFLAGS in addition to the feature detection
specific CFLAGS, so that the following patches can work.

Testing it:

WITHOUT XED in the system, NOT explicitely selecting it:

  $ make O=/tmp/build/perf -C tools/perf install-bin
  $ cat /tmp/build/perf/feature/test-xed.make.output
  cat: /tmp/build/perf/feature/test-xed.make.output: No such file or directory
  $

The feature test is NOT performed, ok.

WITHOUT XED in the system, EXPLICITELY selecting it:

  $ make XED=1 O=/tmp/build/perf -C tools/perf install-bin
  $ cat /tmp/build/perf/feature/test-xed.make.output
  test-xed.c:1:31: fatal error: xed/xed-interface.h: No such file or directory
   #include <xed/xed-interface.h>
                               ^
  compilation terminated.
  $

Ok, the test _IS_ performed, the required devel files are not found, the
build is done without XED.

Now lets try building and installing xed in this system:

  $ git clone https://github.com/intelxed/mbuild.git
  $ git clone https://github.com/intelxed/xed.git
  $ cd xed
  $ ./mfile.py
  $ ./mfile.py install

And lets try enabling XED, informing where 'mfile.py install' installed
it:

  $ make XED=1 XED_DIR=/home/acme/git/xed/kits/xed-install-base-2017-01-23-lin-x86-64/ O=/tmp/build/perf -C tools/perf install-bin
  $ ls -la /tmp/build/perf/feature/test-xed.make.output
  -rw-rw-r--. 1 acme acme 0 Jan 23 10:57 /tmp/build/perf/feature/test-xed.make.output
  $

But it still doesn't link with
/home/acme/git/xed/kits/xed-install-base-2017-01-23-lin-x86-64/lib/libxed.a
because the feature will only be used in the following csets.

Signed-off-by: Andi Kleen <ak@linux.intel.com>
Acked-by: Jiri Olsa <jolsa@kernel.org>
Tested-by: Arnaldo Carvalho de Melo <acme@redhat.com>
Link: http://lkml.kernel.org/r/20170119014150.19218-2-andi@firstfloor.org
Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>