fs.h: Fix build error
Today's -tip fails to build on !CONFIG_BLOCK, due to upstream commit 367a51a ("fs: Add
FITRIM ioctl"):

 include/linux/fs.h:36: error: expected specifier-qualifier-list before ‘uint64_t’
 include/linux/fs.h:36: error: expected specifier-qualifier-list before ‘uint64_t’
 include/linux/fs.h:36: error: expected specifier-qualifier-list before ‘uint64_t’

The commit adds uint64_t type usage to fs.h, but linux/types.h is not
included explicitly - it's only included implicitly via
linux/blk_types.h, and there only if CONFIG_BLOCK is enabled.

Add the explicit #include to fix this.

Ob'grumpy'tester: this commit has a commit date of yesterday, that equals author
date while author != committer - how is that possible? Also, it was merged upstream
a few hours after that.

Signed-off-by: Ingo Molnar <mingo@elte.hu>